### ISSUE TITLE
Cannot complete the install because one or more required items could not be found

### ISSUE THREAD

**Issue by clankill3r** [iloveeclipse/bytecodeoutline#1]
When I try to install the plugin I get the following:

![screen shot 2019-03-05 at 00 59 00](https://user-images.githubusercontent.com/738650/53771226-12c5e180-3ee2-11e9-8377-682f0decf2d3.png)

> Cannot complete the install because one or more required items could not be found.
> Software currently installed: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.0.201901132101-8614914)
> Missing requirement: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview 1.0.0.201901132101-8614914) requires 'osgi.bundle; org.objectweb.asm 7.0.0' but it could not be found
> Cannot satisfy dependency:
> From: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.0.201901132101-8614914)
> To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.bcoview [1.0.0.201901132101-8614914,1.0.0.201901132101-8614914]

Eclipse:
Version: 2018-12 (4.10.0)
Build id: 20181214-0600

**Comment by iloveeclipse** [comment]
You should use latest Eclipse, 4.10 at least, or install asm 7 bundles from Orbit.

**Comment by clankill3r** [comment]
As mentioned in the OP, i'm using eclipse 4.10

**Comment by iloveeclipse** [comment]
*org.objectweb.asm.analysis* and also *org.objectweb.asm.commons* are missing if I try to install on 4.10:
```
Cannot complete the install because one or more required items could not be found.
Software currently installed: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.0.201901132101-8614914)
Missing requirement: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview 1.0.0.201901132101-8614914) requires 'osgi.bundle; org.objectweb.asm.analysis 7.0.0' but it could not be found
Cannot satisfy dependency:
From: Bytecode Outline 1.0.0.201901132101-8614914 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.0.201901132101-8614914)
To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.bcoview [1.0.0.201901132101-8614914,1.0.0.201901132101-8614914]
```
Not sure how you got your error, but I only see this above and as said, the only solution is to install all asm 7.0.0 bundles from Orbit.

**Comment by sarxos** [comment]
Hello there,

I'm dropping this info here for anyone who will get the same error in the future. In my case this happened on Eclipse 2020-03 (4.15).

The solution is to install required dependencies from Orbit repository. If anyone is unaware how to do this, please see description below.

Go to this page:

https://download.eclipse.org/tools/orbit/downloads/

Search for your Eclipse version and click on the link in _Build Name_ column. **DO NOT** use other versions, only the one you have installed, or you will fuk up your Eclipse plugins (I did this and installed bundles from 2019-03 and later had to manually uninstall duplicated bundles).

![image](https://user-images.githubusercontent.com/472658/96731610-bca7f980-13b7-11eb-9de9-a8afd6e93be8.png)

Find the link to the _Orbit Build Repository_ and copy it. You will use it as the Update Site in _Install New Software_ tool.

![image](https://user-images.githubusercontent.com/472658/96731921-15779200-13b8-11eb-9ca5-d75197ed5866.png)

In Eclipse go to `Help > Install New Software`. Add new update site (button _Add_ in the right top corner). Name it accordingly, e.g. I named mine _Orbit 2020-03_ and provide the URL. Save. Then from the drop down box select newly added site, search for the "asm" and select the following:

* ASM Analysis
* ASM Commons
* ASM Core
* ASM Tree
* asm-util

![image](https://user-images.githubusercontent.com/472658/96732557-c0884b80-13b8-11eb-985e-ae0dcea6c291.png)

And finally Next and Finish.

After this is done you can install Bytecode Outline from the Eclipse Marketplace without any errors. After it's installed go to `Window > Show View > Other > Java > Bytecode`. You can also open `Window > Show View > Other > Java > Bytecode Reference` which will display opcode description whenever you select it in the Bytecode View.

![image](https://user-images.githubusercontent.com/472658/96733560-e104d580-13b9-11eb-9c5c-fcf214f209d7.png)

This concludes the description.

Thank you Andrey @iloveeclipse for this awesome tool! Before I found it I always had to search for the bytecodes in the build-in Class File Viewer, which was extremely annoying.

**Comment by pwagland** [comment]
~Thank you @sarxos for this detailed information. When running through these instructions I come across one issue, I have 2020-12, and the link for that goes to: https://download.eclipse.org/tools/orbit/downloads/drops/R20201130205003/ which has asm 5, 8, and 9, but no 7…~

~Is this plugin compatible with 2020-12?~

Edit: Scratch that.  After (yet another) restart, everything just started working with the v9 of the asm libs.
