### ISSUE TITLE
Should this new "1.0.0" version work?

### ISSUE THREAD

**Issue by HenryLoenwind** [iloveeclipse/bytecodeoutline#2]
Even after managing to install it, no views or menu options show up... However, based on the comment on the release here on github, I'm not sure what state it should be in...

**Comment by iloveeclipse** [comment]
It works.

**Comment by tterrag1098** [comment]
Attempting to install it I get this error:

```
Cannot complete the install because one or more required items could not be found.
Software currently installed: Bytecode Outline 1.0.1.202006062100 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.1.202006062100)
Missing requirement: Bytecode Outline 1.0.1.202006062100 (org.eclipse.jdt.bcoview 1.0.1.202006062100) requires 'osgi.bundle; org.objectweb.asm.util 7.0.0' but it could not be found
Cannot satisfy dependency:
From: Bytecode Outline 1.0.1.202006062100 (org.eclipse.jdt.bcoview.feature.feature.group 1.0.1.202006062100)
To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.bcoview [1.0.1.202006062100,1.0.1.202006062100]
```

I have tried installing these dependencies manually from orbit, but nothing changes.

**Comment by tterrag1098** [comment]
I got it to work by installing a few more packages, but this still seems like an issue, these dependencies should be installed automatically right?

**Comment by tterrag1098** [comment]
Finally, and sorry for making this multiple comments, I have the same issue as Henry. I don't see any way to access the view anymore: 
![image](https://user-images.githubusercontent.com/3751664/92065829-62eb6180-ed6e-11ea-8ac1-683b7f0a5c31.png)

**Comment by HenryLoenwind** [comment]
Oops, I completely forgot this ticket. Sorry.

I got those dependencies installed, it took me some time to find the correct package to install and it needs a very specific back version to be installed. However, when I finally got it installed there was nothing to be found of Bytecode Outline.  It showed up as installed package, but that's all.

The old version still works fine (and installs easily when selected)...

**Comment by iloveeclipse** [comment]
Sureit works. 
Update site is
https://raw.githubusercontent.com/iloveeclipse/plugins/latest/

**Comment by ghost** [comment]
> Oops, I completely forgot this ticket. Sorry.
> 
> I got those dependencies installed, it took me some time to find the correct package to install and it needs a very specific back version to be installed. However, when I finally got it installed there was nothing to be found of Bytecode Outline. It showed up as installed package, but that's all.
> 
> The old version still works fine (and installs easily when selected)...

And can you please say what the specific packages you used and give the link ?

**Comment by iloveeclipse** [comment]
Guys, if you don't have Java Development Tools installed in Eclipse, why oh why do you want to install BCO? It requires JDT!
One possible solution is to install that package first:
https://www.eclipse.org/downloads/packages/release/2020-12/r/eclipse-ide-java-developers

**Comment by ghost** [comment]
> Guys, if you don't have Java Development Tools installed in Eclipse, why oh why do you want to install BCO? It requires JDT!
> One possible solution is to install that package first:
> https://www.eclipse.org/downloads/packages/release/2020-12/r/eclipse-ide-java-developers

I've tried with this Eclipse version and i randomly have an error during the installation or the Bytecode window doesn't appear at: [Window > Show View > Other... > Java > Bytecode]
Maybe you changed the name of that window ?
I can't see it anywhere on my Eclipse when i install it successfully.
