### ISSUE TITLE
Repositories down

### ISSUE THREAD

**Issue by ghost** [iloveeclipse/bytecodeoutline#4]
The repositories are down, so i can't install it from the marketplace or from the zip file.
Please fix it.

**Comment by ghost** [comment]
My error btw:
![Capture](https://user-images.githubusercontent.com/48015201/107696012-b238a500-6cb1-11eb-9640-0d1c2e0ae504.PNG)
I tried with Eclipse Photon and 2020-19 and i have the same error.

**Comment by iloveeclipse** [comment]
Have no ideas what are you installing on which Eclipse, but this update site is for sure not down and allows to install latest BCO version : https://raw.githubusercontent.com/iloveeclipse/plugins/latest/

**Comment by ghost** [comment]
I don't want to update it, i want to install it :v
> Have no ideas what are you installing on which Eclipse
👇
> I tried with Eclipse Photon and 2020-19 and i have the same error.

**Comment by iloveeclipse** [comment]
As said, with given update site you can **install** it

**Comment by ghost** [comment]
> As said, with given update site you can **install** it
Seems not because i have the error:
> ![Capture](https://user-images.githubusercontent.com/48015201/107696012-b238a500-6cb1-11eb-9640-0d1c2e0ae504.PNG)

**Comment by iloveeclipse** [comment]
You need Eclipse that contains **JDT**, for example SDK.

**Comment by ghost** [comment]
What do you mean by JDT ? 🤔

**Comment by iloveeclipse** [comment]
Java Development Tools.

**Comment by ghost** [comment]
Where can i find that ?

**Comment by ghost** [comment]
If you're talking about the JDK, i already have it:
![Capture](https://user-images.githubusercontent.com/48015201/107708443-cc7b7e80-6cc3-11eb-92aa-877baf10ec19.PNG)

**Comment by ghost** [comment]
After searching deeply, i found a version which works with my Eclipse version here:
https://bintray.com/iloveeclipse/plugins/BytecodeOutline/2.5.0
I just had to place it in the plugins folder of my Eclipse.
