### ISSUE TITLE
Bytecode View doesnt show up in Eclipse 2020-12

### ISSUE THREAD

**Issue by Jan-Thes** [iloveeclipse/bytecodeoutline#5]
Installed via Market Place without any errors. I then tried also installing Orbit ASM Dependencies (which mostly did not work since they were already installed as a higher version according to Eclipse), but that didn't fix the issue.

### View not found:
![image](https://user-images.githubusercontent.com/59050457/121163361-006c4800-c84f-11eb-8a05-d3742271da48.png)

### Orbit ASM Installation (as descibed in #2 ):
![image](https://user-images.githubusercontent.com/59050457/121165118-51c90700-c850-11eb-91e2-ba8262df218e.png)

![image](https://user-images.githubusercontent.com/59050457/121165400-86d55980-c850-11eb-839b-e4a107111b82.png)

### Eclipse version:
![image](https://user-images.githubusercontent.com/59050457/121163422-0d893700-c84f-11eb-83b3-979e1bc045ea.png)
![image](https://user-images.githubusercontent.com/59050457/121166382-4e824b00-c851-11eb-924a-de6745430f78.png)

### Installed Software:
![image](https://user-images.githubusercontent.com/59050457/121163662-475a3d80-c84f-11eb-8395-ae13940517c2.png)

**Comment by Jan-Thes** [comment]
Seems like i have the same problem like these other 3 people here: https://github.com/iloveeclipse/bytecodeoutline/issues/2, so this is probably a duplicate.

**Comment by iloveeclipse** [comment]
Should actually work with 4.15 - 4.21 Eclipse (I use it on both versions). Any errors in the log? You *have* JDT in your installation for sure? (Eclipse for Enterprise Java package must include that).

**Comment by Jan-Thes** [comment]
I have updated the images above, it is Eclipse for Enterprise Java Developers. I can try in a latest version of Eclipse.

Here is error log where you can see earliest mention of iloveeclipse update site:
![image](https://user-images.githubusercontent.com/59050457/121167300-1a5b5a00-c852-11eb-9e92-703ec3545314.png)

**Comment by iloveeclipse** [comment]
Sorry, no idea how your install is broken / no time for help here. As said, plain SDK will work for sure.

**Comment by Jan-Thes** [comment]
No problem, i can reproduce it with unmodified Eclipse on Windows, here are the steps if anybody else is interested in fixing this.

- Install latest Eclipse for Java EE from https://www.eclipse.org/downloads/packages/release/2021-03/r/eclipse-ide-enterprise-java-and-web-developers
- Install Bytecode Outline from Eclipse Marketplace and restart
-> outliner does not show up in views

Same issue if i change Eclipse -vm arg to point to Oracle JDK 11 instead of bundled JRE that comes with Eclipse. What do you mean with plain SDK? Not using Eclipse JEE but normal version?

**Comment by iloveeclipse** [comment]
Plain SDK is here: https://download.eclipse.org/eclipse/downloads/
It is Java/PDE IDE with no extras installed.
Thanks for your reproduction steps, may be I will find some time to debug that, but I can't guarantee.

**Comment by jevitha** [comment]
Hi,
I see that the plugin does not work on Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2021-06 (4.20.0)
Build id: 20210612-2011

I have the JDT installed as well. 

![image](https://user-images.githubusercontent.com/12469241/123542585-024b6c00-d768-11eb-96ca-d7419e7a3065.png)

**Comment by iloveeclipse** [comment]
@jevitha : please attach error log. Most likely there are conflicts with different, not matching ASM versions installed, similar to #6.

**Comment by jevitha** [comment]
I tried the solution posted at https://github.com/iloveeclipse/bytecodeoutline/issues/1
It seems the asm libraries were installed except for asm-commons v9. After installing that it works now. 
![image](https://user-images.githubusercontent.com/12469241/123543055-6c651080-d76a-11eb-9cb6-e3fa33ebeb3e.png)

Thanks.

**Comment by jevitha** [comment]
All ASM libs are installed in eclipse 2021-06 except asm-commons. So install that to get the plugin working:

![image](https://user-images.githubusercontent.com/12469241/123543384-b8648500-d76b-11eb-900c-6ce6dcc79254.png)

**Comment by iloveeclipse** [comment]
All problems are related to either incomplete list of ASM libraries installed or ASM present in different (conflicting) versions.

Closing this one.

For anyone who needs ASM: please use https://download.eclipse.org/tools/orbit/downloads/latest-I update site and install/update *all* ASM bundles from there.
