### ISSUE TITLE
What is the future of BCO?

### ISSUE THREAD

**Issue by LunarLaurus** [iloveeclipse/bytecodeoutline#8]
G'day! I've been a fan of BCO for many years and have sadly had to find alternatives since updating my primary copy of Eclipse.
Is there any plans to keep this alive?

I've never been able to get it working as outlined in #5 and am stuck loading up an older version of Eclipse just for BCO.
Honestly had kind of hoped that [Eclipse Bug 540436](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540436#c1) would lead to something but it seems like nobody was interested enough to migrate it into JDT directly.

Is there anything I/We can do to try get the ball rolling?

Thanks!

**Comment by iloveeclipse** [comment]
It works fine (well, I'm aware about issues with nested classes etc), but the rest is just OK and I use it with every nightly platform build.

All what you need is to install **all** asm libraries needed. Please use https://download.eclipse.org/tools/orbit/downloads/latest-I update site and install/update all ASM bundles from there.

For the https://bugs.eclipse.org/bugs/show_bug.cgi?id=540436 : I just need someone who could "wrap" BCO in a maven build in the platform [JDT UI repository](https://github.com/eclipse-jdt/eclipse.jdt.ui). I have almost zero maven knowledge, I guess that should be an easy thing for someone looking left and right in JDT.

**Comment by LunarLaurus** [comment]
Thank you Andrey for your very quick reply!  
I'll give it a try, but I did try several times in the past without much success.

Is there anything you're aware of then we could do to get this working out of the box?

**Comment by iloveeclipse** [comment]
> Is there anything you're aware of then we could do to get this working out of the box?

Do you mean installation? It works out of the box if you would follow up this instruction:

1) Download the following file onto your computer: https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.ui/master/releng/org.eclipse.ui.releng/platformUiTools.p2f
2) Select and install the ASM & Bytecode Outline plug-ins referenced by this file by using **File>Import...>Install>Install Software Items from File**.

See also https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364 for the code move to JDT

**Comment by LunarLaurus** [comment]
>Do you mean installation? It works out of the box if you would follow up this instruction:

As in, it shows up in marketplace. you install it, it works. No other work needed ;)

I'll take a look at integration of bco into jdt.ui, the refactoring aspect isn't all that hard.
If you have a reference point for replacing the ByteCode viewer (What classes/etc) I can also poke at that. 
Happy to help out as BCO saves me infinite time! I appreciate the work you've done over the years.

**Comment by iloveeclipse** [comment]
OK, starting with https://download.eclipse.org/eclipse/downloads/drops4/I20230118-0200 the Bytecode Outline bundle is part of the default SDK package and can be installed immediately from this update site: https://download.eclipse.org/eclipse/updates/4.27-I-builds

Once 4.27 will be released, the bundle should be available on https://download.eclipse.org/eclipse/updates/latest/

**Comment by iloveeclipse** [comment]
PS
  @LunarLaurus : thanks for pinging me. I wouldn't otherwise had a motivation to do it for myself only. Always good to hear someone actually uses / likes the stuff.

**Comment by LunarLaurus** [comment]
> PS @LunarLaurus : thanks for pinging me. I wouldn't otherwise had a motivation to do it for myself only. Always good to hear someone actually uses / likes the stuff.

I truly appreciate it! Not enough people truly appreciate the uses of ASM, which is why I'm sure this went mostly unnoticed. While I was happy to try myself, I feel it would have taken much more time to get us to this point today. Now I can finally look into implementing stretch goals. 🙏 🙇‍♀️

**Comment by iloveeclipse** [comment]
> Not enough people truly appreciate the uses of ASM

... which is included in every JDK since at least 1.7 (see `com.sun.xml.internal.ws.org.objectweb.asm.Opcodes` or `jdk.internal.org.objectweb.asm.Opcodes`) ...

Yes, one of really brilliant pieces of software I saw.
